name: "Setup Salesforce and Tools"
description: "Installs Salesforce CLI, required tools, and authenticates via JWT"

inputs:
  jwt_key:
    description: "SFDX JWT Private Key"
    required: true
  client_id:
    description: "Connected App Client ID"
    required: true
  username:
    description: "Salesforce Username"
    required: true
  is_dev_hub:
    description: "Set as Default Dev Hub"
    required: false
    default: "false"
  install_code_analyzer:
    description: "Install @salesforce/plugin-code-analyzer"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Required System Tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Install Salesforce CLI
      shell: bash
      run: |
        if ! command -v sf &> /dev/null; then
          npm install @salesforce/cli --global
        fi

    - name: Install Essential Plugins
      if: ${{ inputs.install_code_analyzer == 'true' }}
      shell: bash
      run: |
        echo y | sf plugins install sfdx-git-delta @salesforce/plugin-code-analyzer

    - name: Authenticate via JWT
      shell: bash
      run: |
        echo "${{ inputs.jwt_key }}" > portfolio.key

        LOGIN_FLAGS="--client-id ${{ inputs.client_id }} \
                     --jwt-key-file portfolio.key \
                     --username ${{ inputs.username }} \
                     --alias portfolio \
                     --instance-url https://login.salesforce.com"

        if [ "${{ inputs.is_dev_hub }}" = "true" ]; then
          sf org login jwt $LOGIN_FLAGS --set-default-dev-hub
        else
          sf org login jwt $LOGIN_FLAGS
        fi

        rm portfolio.key
